# Project info
title:      Docta example
logo:       img/logo.png
copyright:  '&copy; 2014, 05Bit <a href="http://05bit.com" target="_blank">http://05bit.com</a>'

# Data structure
chapters:
    # Main chapters
    - index:            index.md
      input_path:       .
    # Scan sources for README.md
    - base_nav_path:    source
      index:            README.md
      input_path:       ..

# Rendering
output:
  html:
    build_path: ./_html
    theme:
        icons: awesome
        #icons: glyphicon
    main_menu:
        - title:  Overview
          url:    ''
        - title:  Install
          url:    chapter/install/
          icon:   download
        - title:  Development
          url:    https://github.com/05bit/python-docta
resources:  ./_resources
templates:  ./_templates

# Serving html
server:
    host:       127.0.0.1
    port:       8000
    base_url:   /
    assets_url: assets/
    watch:      ['*.html', '*.md']
