# Project info
title:      Docta
logo:       img/logo.png
copyright:  '&copy; 2014, 05Bit <a href="http://05bit.com" target="_blank">http://05bit.com</a>'

# Data structure
chapters:
    # Main chapters
    - index:            index.md
      input_path:       ./_pages

# Rendering
output:
  html:
    build_path: .
    theme:
        icons: awesome
        #icons: glyphicon
    main_menu:
        - title:  Quickstart
          url:    '/#quickstart'
        - title:  Tutorial
          url:    tutorial/
        - title:  Install
          url:    '/#install'
          icon:   download
# resources:  ./_resources
templates:  ./_templates

# Serving html
server:
    host:       127.0.0.1
    port:       8000
    base_url:   /
    assets_url: assets/
    watch:      ['*.html', '*.md']
